from dockerphile.structures.add_t import ADD, ADD_t
from dockerphile.structures.arg_t import ARG, ARG_t
from dockerphile.structures.cmd_t import CMD, CMD_t
from dockerphile.structures.comment_t import COMMENT, COMMENT_t
from dockerphile.structures.copy_t import COPY, COPY_t
from dockerphile.structures.entrypoint_t import ENTRYPOINT, ENTRYPOINT_t
from dockerphile.structures.env_t import ENV, ENV_t
from dockerphile.structures.escape_t import ESCAPE, ESCAPE_t
from dockerphile.structures.expose_t import EXPOSE, EXPOSE_t
from dockerphile.structures.from_t import FROM, FROM_t
from dockerphile.structures.healthcheck_t import HEALTHCHECK, HEALTHCHECK_t
from dockerphile.structures.label_t import LABEL, LABEL_t
from dockerphile.structures.onbuild_t import ONBUILD, ONBUILD_t
from dockerphile.structures.run_t import RUN, RUN_t
from dockerphile.structures.shell_t import SHELL, SHELL_t
from dockerphile.structures.stopsignal_t import STOPSIGNAL, STOPSIGNAL_t
from dockerphile.structures.user_t import USER, USER_t
from dockerphile.structures.volume_t import VOLUME, VOLUME_t
from dockerphile.structures.workdir_t import WORKDIR, WORKDIR_t
